### ISSUE TITLE
About disparity estimator

### ISSUE THREAD

**Issue by Nianzhen-GU** [keunsoo-ko/LFSR-AFR#1]
I'm interested in the method you used to calculate the optical flow. However, I want to know whether it can generate accurate results when two images have large disparity, say, shot from different angles. Also, if I only need to calculate the disparity between two images and warp one to the other, how should I change and use your code? Thanks a lot.

**Comment by keunsoo-ko** [comment]
Thank you for your interest.

Since our disparity estimator consists of a few convolutional layers, 
it may be hard to generate accurate results when two images have a large disparity.

If you want to change the architecture of our disparity estimator, we should change the functions of "Flow" and "Flow_forward" in lib/model.py

**Comment by Nianzhen-GU** [comment]
Thanks a lot!
